quarkus.log.level=INFO

quarkus.vault.url=http://vault.shared-services.svc.cluster.local:8200
%dev.quarkus.vault.url=http://localhost:8200
quarkus.vault.secret-config-kv-path=database/config,application/config
quarkus.vault.kv-secret-engine-mount-path=verifier
quarkus.vault.authentication.client-token=hvs.2RlTdQT25Km7cvXeUAX6KvQE
quarkus.vault.kv-secret-engine-version=2

%prod.kafka.bootstrap.servers=kafka-yaci-role-verifier.d.aivencloud.com:23119
%dev.kafka.bootstrap.servers=localhost:9092

# Aiven SSL — cert values injected from Vault (verifier/data/application/config)
%prod.kafka.security.protocol=SSL
%prod.kafka.ssl.truststore.type=PEM
%prod.kafka.ssl.truststore.certificates=${kafka.ssl.ca}
%prod.kafka.ssl.keystore.type=PEM
%prod.kafka.ssl.keystore.certificate.chain=${kafka.ssl.cert}
%prod.kafka.ssl.keystore.key=${kafka.ssl.key}


mp.messaging.outgoing.wallet-tracking-out.connector=smallrye-kafka
mp.messaging.outgoing.wallet-tracking-out.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
mp.messaging.outgoing.wallet-tracking-out.topic=tracking-commands

mp.messaging.incoming.cardano-utxo-updates.connector=smallrye-kafka
mp.messaging.incoming.cardano-utxo-updates.value.deserializer=dk.panos.promofacie.config.UtxoTransactionPayloadDeserializer
mp.messaging.incoming.cardano-utxo-updates.failure-strategy=ignore

mp.messaging.incoming.transactions.connector=smallrye-kafka
mp.messaging.incoming.transactions.value.deserializer=dk.panos.promofacie.config.TransactionMessageDeserializer
mp.messaging.incoming.transactions.failure-strategy=ignore

quarkus.datasource.trust-all=true
quarkus.datasource.username=${POSTGRES_USERNAME}
quarkus.datasource.password=${POSTGRES_PASSWORD}
quarkus.datasource.jdbc.url=jdbc:postgresql://db-postgresql-ams3-94724-do-user-17259409-0.i.db.ondigitalocean.com:25060/verifier?sslmode=require
quarkus.datasource.db-kind=postgresql
quarkus.hibernate-orm.log.sql=false
quarkus.hibernate-orm.schema-management.strategy=update
discord_api_key=${DISCORD_API_KEY}
blockfrost_api_key=${BLOCKFROST_API_KEY}

quarkus.oidc.auth-server-url=https://login.promofacie.site/realms/dashboard
quarkus.oidc.client-id=phoenix-client
quarkus.oidc.credentials.secret=4O4miVEcONwUs5d4PKy8ks7FlLIrWjdn
quarkus.oidc.application-type=service
quarkus.datasource.jdbc.max-size=5